2024-08-22 20:39:16.092373: Exception in getRequest() https://proxylist.geonode.comddd/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc: HTTPSConnectionPool(host='proxylist.geonode.comddd', port=443): Max retries exceeded with url: /api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x10d47c890>: Failed to resolve 'proxylist.geonode.comddd' ([Errno 8] nodename nor servname provided, or not known)"))
2024-08-22 20:39:28.829322: Exception in getProxyListFromGeonode(): Sorry, no numbers below zero
2024-08-22 20:40:35.119258: Exception in getRequest() https://proxylist.geonode.comddd/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc: HTTPSConnectionPool(host='proxylist.geonode.comddd', port=443): Max retries exceeded with url: /api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1088addc0>: Failed to resolve 'proxylist.geonode.comddd' ([Errno 8] nodename nor servname provided, or not known)"))
2024-08-22 20:40:35.900397: Exception in getProxyListFromGeonode(): Sorry, no numbers below zero
2024-08-22 20:41:28.511880: Exception in getRequest() https://proxylist.geonode.comddd/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc: HTTPSConnectionPool(host='proxylist.geonode.comddd', port=443): Max retries exceeded with url: /api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x107a48710>: Failed to resolve 'proxylist.geonode.comddd' ([Errno 8] nodename nor servname provided, or not known)"))
2024-08-22 20:41:30.313892: Exception in getProxyListFromGeonode(): Sorry, no numbers below zero
2024-08-22 20:42:36.163243: Exception in getRequest() https://proxylist.geonode.comddd/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc: HTTPSConnectionPool(host='proxylist.geonode.comddd', port=443): Max retries exceeded with url: /api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1047548c0>: Failed to resolve 'proxylist.geonode.comddd' ([Errno 8] nodename nor servname provided, or not known)"))
2024-08-22 20:42:38.813319: Exception in getProxyListFromGeonode(): Sorry, no numbers below zero
2024-08-22 20:43:44.446532: Exception in getRequest() https://proxylist.geonode.comddd/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc: HTTPSConnectionPool(host='proxylist.geonode.comddd', port=443): Max retries exceeded with url: /api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x10a7f3f80>: Failed to resolve 'proxylist.geonode.comddd' ([Errno 8] nodename nor servname provided, or not known)"))
2024-08-22 20:43:45.200432: Exception in getProxyListFromGeonode(): Sorry, no numbers below zero
2024-08-22 20:55:07.964647: Exception in getRequest() https://proxylist.geonode.comddd/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc: HTTPSConnectionPool(host='proxylist.geonode.comddd', port=443): Max retries exceeded with url: /api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x10d0880b0>: Failed to resolve 'proxylist.geonode.comddd' ([Errno 8] nodename nor servname provided, or not known)"))
2024-08-22 20:55:07.965338: Exception in getProxyListFromGeonode(): Sorry, no numbers below zero
2024-08-22 20:55:57.354579: Exception in getRequest() https://proxylist.geonode.comddd/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc: HTTPSConnectionPool(host='proxylist.geonode.comddd', port=443): Max retries exceeded with url: /api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x10d6560c0>: Failed to resolve 'proxylist.geonode.comddd' ([Errno 8] nodename nor servname provided, or not known)"))
2024-08-22 20:55:57.356238: Exception in getProxyListFromGeonode(): Sorry, no numbers below zero
2024-08-22 20:56:22.003124: Exception in getRequest() https://proxylist.geonode.comddd/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc: HTTPSConnectionPool(host='proxylist.geonode.comddd', port=443): Max retries exceeded with url: /api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x10d6578c0>: Failed to resolve 'proxylist.geonode.comddd' ([Errno 8] nodename nor servname provided, or not known)"))
2024-08-22 20:56:22.003715: Exception in getProxyListFromGeonode(): Sorry, no numbers below zero
2024-08-22 20:57:19.796432: Exception in getRequest() https://proxylist.geonode.comddd/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc: HTTPSConnectionPool(host='proxylist.geonode.comddd', port=443): Max retries exceeded with url: /api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x10ac18ec0>: Failed to resolve 'proxylist.geonode.comddd' ([Errno 8] nodename nor servname provided, or not known)"))
2024-08-22 20:57:19.797132: Exception in getProxyListFromGeonode(): Sorry, no numbers below zero
2024-08-22 20:58:05.996156: Exception in getRequest() https://proxylist.geonode.comddd/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc: HTTPSConnectionPool(host='proxylist.geonode.comddd', port=443): Max retries exceeded with url: /api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x108a50950>: Failed to resolve 'proxylist.geonode.comddd' ([Errno 8] nodename nor servname provided, or not known)"))
2024-08-22 20:58:05.996515: Exception in getProxyListFromGeonode(): Sorry, no numbers below zero
2024-08-22 20:59:31.206256: Exception in getRequest() https://proxylist.geonode.comddd/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc: HTTPSConnectionPool(host='proxylist.geonode.comddd', port=443): Max retries exceeded with url: /api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x111cec590>: Failed to resolve 'proxylist.geonode.comddd' ([Errno 8] nodename nor servname provided, or not known)"))
2024-08-22 20:59:31.206636: Exception in getProxyListFromGeonode(): Sorry, no numbers below zero
2024-08-22 21:00:32.631415: Exception in getRequest() https://proxylist.geonode.comddd/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc: HTTPSConnectionPool(host='proxylist.geonode.comddd', port=443): Max retries exceeded with url: /api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x109dff6b0>: Failed to resolve 'proxylist.geonode.comddd' ([Errno 8] nodename nor servname provided, or not known)"))
2024-08-22 21:00:32.632022: Exception in getProxyListFromGeonode(): Sorry, no numbers below zero
2024-08-22 21:01:23.296476: Exception in getRequest() https://proxylist.geonode.comddd/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc: HTTPSConnectionPool(host='proxylist.geonode.comddd', port=443): Max retries exceeded with url: /api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x10add40b0>: Failed to resolve 'proxylist.geonode.comddd' ([Errno 8] nodename nor servname provided, or not known)"))
2024-08-22 21:01:23.296760: Exception in getProxyListFromGeonode(): Sorry, no numbers below zero
2024-08-22 21:02:32.161022: Exception in getRequest() https://proxylist.geonode.comddd/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc: HTTPSConnectionPool(host='proxylist.geonode.comddd', port=443): Max retries exceeded with url: /api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x10b0e6930>: Failed to resolve 'proxylist.geonode.comddd' ([Errno 8] nodename nor servname provided, or not known)"))
2024-08-22 21:02:32.162407: Exception in getProxyListFromGeonode(): Sorry, no numbers below zero
2024-08-22 21:05:54.525021: Exception in getRequest() https://proxylist.geonode.comddd/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc: HTTPSConnectionPool(host='proxylist.geonode.comddd', port=443): Max retries exceeded with url: /api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1062e47d0>: Failed to resolve 'proxylist.geonode.comddd' ([Errno 8] nodename nor servname provided, or not known)"))
2024-08-22 21:05:54.525256: Exception in getProxyListFromGeonode(): Sorry, no numbers below zero
